const plotting_pkgs = [ "Gadfly",
                        "GR",
                        "Plots",
                        "VegaLite",
                        "StatPlots",
                        "Plotly",
                        "PlotlyJS",
                        "UnicodePlots",
                        "StatsPlots",
                        "GraphRecipes",
                        "DataVoyager"]
