const datasci_pkgs = [  "ClassImbalance",
                        "Clustering",
                        "DecisionTree",
                        "Flux",
                        "GLM",
                        "GLMNet",
                        "HypothesisTests",
                        "Knet",
                        "MixedModels",
                        "ROCAnalysis",
                        "LIBSVM",
                        "TextAnalysis",
                        "WordTokenizers",
                        "Ipopt",
                        "JuMP",
                        "Primes",
                        "Distributions",
                        "Roots",
                        "Optim",
                        "StatsBase",
                        "MLDatasets",
                        "Images",
                        "TSne",
                        "ProgressMeter",
                        "DataFramesMeta",
                        "SymPy",
                        "TableView",
                        "Weave",
                        "QuadGK",
                        "NLopt",
                        "LaTeXStrings",
                        "Feather"
                    ]

const dataset_pkgs = ["VegaDatasets", "RDatasets"]
